### ISSUE TITLE
Error: cannot use 'throw' with exceptions disabled

### ISSUE THREAD

**Issue by jcjolley** [kevinschaich/dotfiles#1]
Whenever you throw something, the linter complains with the text of the title of this issue.

**Comment by kevinschaich** [comment]
@jcjolley Can you give a little more info on your setup? Which linter is complaining about which file?

**Comment by jcjolley** [comment]
For sure!  I am on Win10, Sublime Test 3 Build 3103.
SublimeLinter-contrib-clang is the linter that is complaining.
*OS:                    *Windows 10
*Sublime Build:   *3103
*Linter:                *SublimeLinter - SublimeLinter-contrib-clang
*Clang -v output:*
clang version 3.8.0 (branches/release_38)
Target: x86_64-pc-windows-msvc
Thread model: posix
InstalledDir: C:\Program Files\LLVM\bin
*SublimeLinter-contrib-clang settings:*
{
    "user": {
        "debug": false,
        "delay": 0.25,
        "error_color": "D02000",
        "gutter_theme":
"Packages/SublimeLinter/gutter-themes/Default/Default.gutter-theme",
        "gutter_theme_excludes": [],
        "lint_mode": "background",
        "linters": {
            "clang": {
                "@disable": false,
                "args": [],
                "excludes": [],
                "extra_flags": "-Wall -std=c++14",
                "include_dirs": [
                    "${project_folder}"
                ]
            }
        },
        "mark_style": "outline",
        "no_column_highlights_line": false,
        "passive_warnings": false,
        "paths": {
            "linux": [],
            "osx": [],
            "windows": []
        },
        "python_paths": {
            "linux": [],
            "osx": [],
            "windows": []
        },
        "rc_search_limit": 3,
        "shell_timeout": 10,
        "show_errors_on_save": true,
        "show_marks_in_minimap": true,
        "syntax_map": {
            "html (django)": "html",
            "html (rails)": "html",
            "html 5": "html",
            "php": "html",
            "python django": "python"
        },
        "warning_color": "DDB700",
        "wrap_find": true
    }
}

I've attached two pictures of the error.


[image: 2016-04-03
00_10_16-C__Users_josh_Documents_cs470_secure_string_myUtils.h (cs470fp) -
Sublime Text.png][image: 2016-04-03 00_10_54-.png]

Please let me know if there is anything else I can do to help explain.
Thanks for your help!

**Comment by jcjolley** [comment]
For sure!  I am on Win10, Sublime Test 3 Build 3103.  SublimeLinter-contrib-clang is the linter that is complaining.
OS:                    Windows 10
Sublime Build:   3103
Linter:                SublimeLinter - SublimeLinter-contrib-clang
Clang -v output:
clang version 3.8.0 (branches/release_38)
Target: x86_64-pc-windows-msvc
Thread model: posix
InstalledDir: C:\Program Files\LLVM\bin
SublimeLinter-contrib-clang settings:
{
    "user": {
        "debug": false,
        "delay": 0.25,
        "error_color": "D02000",
        "gutter_theme": "Packages/SublimeLinter/gutter-themes/Default/Default.gutter-theme",
        "gutter_theme_excludes": [],
        "lint_mode": "background",
        "linters": {
            "clang": {
                "@disable": false,
                "args": [],
                "excludes": [],
                "extra_flags": "-Wall -std=c++14",
                "include_dirs": [
                    "${project_folder}"
                ]
            }
        },
        "mark_style": "outline",
        "no_column_highlights_line": false,
        "passive_warnings": false,
        "paths": {
            "linux": [],
            "osx": [],
            "windows": []
        },
        "python_paths": {
            "linux": [],
            "osx": [],
            "windows": []
        },
        "rc_search_limit": 3,
        "shell_timeout": 10,
        "show_errors_on_save": true,
        "show_marks_in_minimap": true,
        "syntax_map": {
            "html (django)": "html",
            "html (rails)": "html",
            "html 5": "html",
            "php": "html",
            "python django": "python"
        },
        "warning_color": "DDB700",
        "wrap_find": true
    }
}

I've attached two pictures of the error.  

![2016-04-03 00_10_16-c__users_josh_documents_cs470_secure_string_myutils h cs470fp - sublime text](https://cloud.githubusercontent.com/assets/2086176/14231051/1b51ac70-f931-11e5-801c-05d1c3aa6181.png)
![2016-04-03 00_10_54-](https://cloud.githubusercontent.com/assets/2086176/14231050/1b51a04a-f931-11e5-9d17-738ca4bee4fe.png)


Please let me know if there is anything else I can do to help explain.
Thanks for your help!

**Comment by jcjolley** [comment]
Adding `-fcxx-exceptions` to extra flags resolved the issue.

**Comment by kevinschaich** [comment]
Thanks for posting your solution here! I'll go ahead and mark as resolved.
